//! Player-related effects.
//!
//! This module contains effects that modify player state,
//! such as adding counters (poison, energy, experience),
//! win/lose conditions, turn manipulation, and emblem creation.

mod additional_land_plays;
mod additional_phases;
mod ascend;
mod become_monarch;
mod cascade;
mod cast_source;
mod cast_tagged;
mod choose_card_name;
mod choose_card_type;
mod choose_color;
mod choose_creature_type;
mod choose_land_type;
mod choose_named_option;
mod choose_player;
mod control_combat_choices;
mod control_player;
mod create_emblem;
pub(crate) mod die_roll_transaction;
mod discover;
mod draw_the_game;
mod end_combat_phase;
mod end_turn;
mod energy_counters;
mod exile_instead_of_graveyard;
mod exile_then_grant_play;
mod exile_until_match_cast;
mod exile_until_match_grant_play;
mod experience_counters;
mod extra_turn;
mod extra_turn_after_next_turn;
mod flip_coin;
mod grant;
mod grant_by_spec;
mod grant_next_spell_ability;
mod grant_next_spell_cost_reduction;
mod grant_play_tagged;
mod grant_tagged_spell_free_cast_until_end_of_turn;
mod grant_tagged_spell_life_cost_by_mana_value;
mod lose_the_game;
mod may_cast_matching_spell;
mod may_cast_miracle;
mod pay_energy;
mod play_subgame;
mod player_counters;
mod poison_counters;
mod radiation;
mod restart_game;
mod reverse_turn_order;
mod ring_tempts_you;
mod roll_dice_choose_result;
mod roll_die;
mod choose_number_at_random;
mod runtime_helpers;
mod skip_combat_phases;
mod skip_combat_phases_this_turn;
mod skip_draw_step;
mod skip_main_phases_this_turn;
mod skip_next_combat_phase_this_turn;
mod skip_turn;
mod speed;
mod take_initiative;
mod ticket_counters;
mod venture_into_dungeon;
mod win_the_game;

pub use additional_land_plays::AdditionalLandPlaysEffect;
pub use additional_phases::{AdditionalPhase, AdditionalPhasesEffect};
pub use ascend::AscendEffect;
pub use become_monarch::BecomeMonarchEffect;
pub use cascade::CascadeEffect;
pub use cast_source::CastSourceEffect;
pub use cast_tagged::CastTaggedEffect;
pub use choose_card_name::ChooseCardNameEffect;
pub(crate) use choose_card_name::{split_chosen_card_names, synthetic_chosen_name_snapshot};
pub use choose_card_type::ChooseCardTypeEffect;
pub use choose_color::ChooseColorEffect;
pub use choose_creature_type::ChooseCreatureTypeEffect;
pub use choose_land_type::ChooseLandTypeEffect;
pub use choose_named_option::ChooseNamedOptionEffect;
pub use choose_player::ChoosePlayerEffect;
pub use control_combat_choices::ControlCombatChoicesThisTurnEffect;
pub use control_player::ControlPlayerEffect;
pub use create_emblem::CreateEmblemEffect;
pub use discover::DiscoverEffect;
pub use draw_the_game::DrawTheGameEffect;
pub use end_combat_phase::EndCombatPhaseEffect;
pub use end_turn::EndTurnEffect;
pub use energy_counters::EnergyCountersEffect;
pub use exile_instead_of_graveyard::ExileInsteadOfGraveyardEffect;
pub use exile_then_grant_play::ExileThenGrantPlayEffect;
pub use exile_until_match_cast::ExileUntilMatchCastEffect;
pub use exile_until_match_grant_play::ExileUntilMatchGrantPlayEffect;
pub use experience_counters::ExperienceCountersEffect;
pub use extra_turn::ExtraTurnEffect;
pub use extra_turn_after_next_turn::ExtraTurnAfterNextTurnEffect;
pub use flip_coin::FlipCoinEffect;
pub use grant::GrantEffect;
pub use grant_by_spec::GrantBySpecEffect;
pub use grant_next_spell_ability::GrantNextSpellAbilityEffect;
pub use grant_next_spell_cost_reduction::GrantNextSpellCostReductionEffect;
pub use grant_play_tagged::{GrantPlayTaggedDuration, GrantPlayTaggedEffect};
pub use grant_tagged_spell_free_cast_until_end_of_turn::GrantTaggedSpellFreeCastUntilEndOfTurnEffect;
pub use grant_tagged_spell_life_cost_by_mana_value::GrantTaggedSpellLifeCostByManaValueEffect;
pub use lose_the_game::LoseTheGameEffect;
pub use may_cast_matching_spell::MayCastMatchingSpellWithoutPayingManaCostEffect;
pub use may_cast_miracle::MayCastForMiracleCostEffect;
pub use pay_energy::{PayAnyEnergyEffect, PayAnyLifeEffect, PayEnergyEffect};
pub use play_subgame::PlaySubgameEffect;
pub use player_counters::PlayerCountersEffect;
pub use poison_counters::PoisonCountersEffect;
pub use radiation::RadiationEffect;
pub use restart_game::RestartGameEffect;
pub use reverse_turn_order::ReverseTurnOrderEffect;
pub use ring_tempts_you::RingTemptsYouEffect;
pub use roll_dice_choose_result::RollDiceChooseResultEffect;
pub use roll_die::RollDieEffect;
pub use choose_number_at_random::ChooseNumberAtRandomEffect;
pub use skip_combat_phases::SkipCombatPhasesEffect;
pub use skip_combat_phases_this_turn::SkipCombatPhasesThisTurnEffect;
pub use skip_draw_step::SkipDrawStepEffect;
pub use skip_main_phases_this_turn::SkipMainPhasesThisTurnEffect;
pub use skip_next_combat_phase_this_turn::SkipNextCombatPhaseThisTurnEffect;
pub use skip_turn::SkipTurnEffect;
pub use speed::{IncreaseSpeedEffect, ReduceSpeedEffect};
pub use take_initiative::TakeInitiativeEffect;
pub use ticket_counters::TicketCountersEffect;
pub use venture_into_dungeon::VentureIntoDungeonEffect;
pub use win_the_game::WinTheGameEffect;

mod reveal_chosen_subtype;
pub use reveal_chosen_subtype::RevealChosenSubtypeEffect;
