[package]
name = "ironsmith-compiler-resolve"
version = "0.1.0"
edition = "2024"

[dependencies]
ironsmith-core = { path = "../ironsmith-core", default-features = false, features = ["serde"] }
ironsmith-compiler-source = { path = "../ironsmith-compiler-source", default-features = false }
ironsmith-compiler-semantic = { path = "../ironsmith-compiler-semantic", default-features = false }

[features]
default = []
compiler-internal-tests = []
serialization = []

[lib]
path = "src/lib.rs"
