//! Frozen full-card conditional damage regressions. Authored and UNRUN.
use ironsmith::card::{CardBuilder, PowerToughness};
use ironsmith::cards::CardDefinition;
use ironsmith::color::ColorSet;
use ironsmith::continuous::{EffectTarget, Modification};
use ironsmith::decision::{DecisionMaker, LegalAction, SelectFirstDecisionMaker, compute_legal_actions};
use ironsmith::decisions::context::{BooleanContext, NumberContext, SelectObjectsContext, SelectOptionsContext, TargetsContext};
use ironsmith::effect::Until;
use ironsmith::effects::{ApplyContinuousEffect, EffectContext, EffectExecutor};
use ironsmith::events::{DamageEvent, DamageTarget};
use ironsmith::game_loop::{PriorityLoopState, PriorityResponse, apply_decision_context_with_dm,
    apply_priority_response_with_dm, drain_pending_trigger_events,
    extract_target_requirements_from_program_with_modes, put_triggers_on_stack_with_dm,
    resolve_stack_entry_with};
use ironsmith::game_state::{Phase, StackEntry, TargetAssignment};
use ironsmith::mana::ManaSymbol;
use ironsmith::triggers::TriggerQueue;
use ironsmith::{CardId, CardType, GameProgress, GameState, ObjectId, PlayerId, Subtype, Supertype, Target, Zone};
use ironsmith_compiled_artifact::CompiledCardArtifact;
use ironsmith_compiler::parse_loss;
use ironsmith_compiler_runtime::{compile_to_artifact, compile_to_runtime_definition};
use ironsmith_runtime_catalog::artifact_materializer::{encode_runtime_definition,
    materialize_artifact, materialize_definition};

const A: PlayerId = PlayerId::from_index(0);
const B: PlayerId = PlayerId::from_index(1);
const ADOPTED: &[&str] = &["Burst Lightning", "Roil Eruption", "Shivan Fire", "Frost Bite",
    "Burning Hands", "Voltage Surge", "Akoum Hellkite"];

fn card_text(name: &str) -> String {
    let rows: Vec<serde_json::Value> = serde_json::from_str(include_str!(
        "../../../fixtures/conditional_damage_amounts.json.fixture")).unwrap();
    let row = rows.iter().find(|row| row["name"] == name).unwrap();
    let mut lines = vec![format!("Mana cost: {}", row["mana_cost"].as_str().unwrap()),
        format!("Type: {}", row["type_line"].as_str().unwrap())];
    if let (Some(power), Some(toughness)) = (row["power"].as_str(), row["toughness"].as_str()) {
        lines.push(format!("Power/Toughness: {power}/{toughness}"));
    }
    lines.push(row["oracle_text"].as_str().unwrap().into());
    lines.join("\n")
}

fn definitions_text(name: &str, text: &str) -> [CardDefinition; 3] {
    let (result, loss) = parse_loss::capture(|| compile_to_runtime_definition(name, text, false));
    let direct = result.unwrap_or_else(|error| panic!("direct {name}: {error}"));
    assert!(!loss.is_lossy(), "direct {name}: {}", loss.reasons_text());
    let (result, loss) = parse_loss::capture(|| compile_to_artifact(name, text, false));
    let (artifact, _) = result.unwrap_or_else(|error| panic!("artifact {name}: {error}"));
    assert!(!loss.is_lossy(), "artifact {name}: {}", loss.reasons_text());
    artifact.validate().unwrap();
    let decoded = CompiledCardArtifact::from_json(&artifact.to_json().unwrap()).unwrap();
    assert_eq!(artifact, decoded);
    let native = encode_runtime_definition(direct.clone()).unwrap();
    let native = materialize_definition(serde_json::from_slice(&serde_json::to_vec(&native).unwrap()).unwrap()).unwrap();
    let definitions = [direct, materialize_artifact(&decoded).unwrap(), native];
    let rendered = ironsmith_text::canonical_compiled_lines(&definitions[0]);
    for definition in &definitions {
        assert!(!ironsmith::cards::generated_definition_has_unimplemented_content(definition));
        assert_eq!(ironsmith_text::canonical_compiled_lines(definition), rendered);
    }
    definitions
}

fn definitions(name: &str) -> [CardDefinition; 3] {
    definitions_text(name, &card_text(name))
}

// Independent authored expectations, not snapshots generated by the compiler
// under test. Canonical rules omit reminder text; every executable sentence,
// amount, recipient, condition and optional cost remains in these snapshots.
fn expected_rules(name: &str) -> &'static str {
    match name {
        "Burst Lightning" => "Kicker {4}\nBurst Lightning deals 2 damage to any target. If this spell was kicked, it deals 4 damage instead.",
        "Roil Eruption" => "Kicker {5}\nRoil Eruption deals 3 damage to any target. If this spell was kicked, it deals 5 damage instead.",
        "Shivan Fire" => "Kicker {4}\nShivan Fire deals 2 damage to target creature. If this spell was kicked, it deals 4 damage instead.",
        "Frost Bite" => "Frost Bite deals 2 damage to target creature or planeswalker. If you control three or more snow permanents, it deals 3 damage instead.",
        "Burning Hands" => "Burning Hands deals 2 damage to target creature or planeswalker. If that permanent is green, Burning Hands deals 6 damage instead.",
        "Voltage Surge" => "As an additional cost to cast this spell, you may sacrifice an artifact.\nVoltage Surge deals 2 damage to target creature or planeswalker. If this spell's additional cost was paid, Voltage Surge deals 4 damage instead.",
        "Akoum Hellkite" => "Flying\nLandfall — Whenever a land you control enters, this creature deals 1 damage to any target. If that land is a Mountain, this creature deals 2 damage instead.",
        _ => panic!("missing independent full-card expectation: {name}"),
    }
}

fn terminal_punctuation_normalized(text: &str) -> String {
    text.lines().map(|line| line.trim().trim_end_matches('.')).collect::<Vec<_>>().join("\n")
}

fn game() -> GameState {
    let mut game = GameState::new(vec!["Alice".into(), "Bob".into()], 20);
    game.turn.active_player = A;
    game.turn.priority_player = Some(A);
    game.turn.phase = Phase::FirstMain;
    game.turn.step = None;
    for color in [ManaSymbol::Red, ManaSymbol::Colorless] {
        game.player_mut(A).unwrap().mana_pool.add(color, 20);
    }
    game
}

fn permanent(game: &mut GameState, owner: PlayerId, kind: CardType, snow: bool) -> ObjectId {
    let card = CardBuilder::new(CardId::new(), "Damage witness")
        .card_types(vec![kind])
        .supertypes(if snow { vec![Supertype::Snow] } else { vec![] })
        .power_toughness(PowerToughness::fixed(1, 20)).build();
    game.create_object_from_card(&card, owner, Zone::Battlefield)
}

fn change(game: &mut GameState, target: ObjectId, modification: Modification) {
    ApplyContinuousEffect::new(EffectTarget::Specific(target), modification, Until::Forever)
        .execute(game, &mut EffectContext::new_default(target, A)).unwrap();
    game.refresh_continuous_state().unwrap();
}

#[derive(Default)]
struct Choices {
    targets: Vec<Target>,
    optional: bool,
    sacrifice: Option<ObjectId>,
    x: u32,
    target_questions: usize,
}
impl DecisionMaker for Choices {
    fn decide_boolean(&mut self, _: &GameState, _: &BooleanContext) -> bool { self.optional }
    fn decide_options(&mut self, game: &GameState, ctx: &SelectOptionsContext) -> Vec<usize> {
        if ctx.description.starts_with("Choose optional costs") {
            return if self.optional {
                vec![ctx.options.iter().find(|option| option.legal).unwrap().index]
            } else { vec![] };
        }
        SelectFirstDecisionMaker.decide_options(game, ctx)
    }
    fn decide_number(&mut self, game: &GameState, ctx: &NumberContext) -> u32 {
        if ctx.is_x_value { self.x } else { SelectFirstDecisionMaker.decide_number(game, ctx) }
    }
    fn decide_objects(&mut self, game: &GameState, ctx: &SelectObjectsContext) -> Vec<ObjectId> {
        if let Some(id) = self.sacrifice {
            assert!(ctx.candidates.iter().any(|candidate| candidate.id == id && candidate.legal));
            vec![id]
        } else { SelectFirstDecisionMaker.decide_objects(game, ctx) }
    }
    fn decide_targets(&mut self, _: &GameState, ctx: &TargetsContext) -> Vec<Target> {
        self.target_questions += 1;
        assert_eq!(ctx.requirements.len(), 1, "one original declaration");
        for target in &self.targets { assert!(ctx.requirements[0].legal_targets.contains(target)); }
        self.targets.clone()
    }
}

fn cast(game: &mut GameState, definition: &CardDefinition, dm: &mut Choices) -> ObjectId {
    let id = game.create_object_from_definition(definition, A, Zone::Hand);
    let action = compute_legal_actions(game, A).unwrap().into_iter().find(|action|
        matches!(action, LegalAction::CastSpell { spell_id, .. } if *spell_id == id)).unwrap();
    let mut queue = TriggerQueue::new();
    let mut state = PriorityLoopState::new(2);
    let mut progress = apply_priority_response_with_dm(game, &mut queue, &mut state,
        &PriorityResponse::PriorityAction(action), dm).unwrap();
    for _ in 0..64 {
        if !state.has_pending_action() {
            let entry = game.stack.last().unwrap();
            assert_eq!(entry.targets, dm.targets);
            assert_eq!(entry.target_assignments.len(), 1);
            assert_eq!(dm.target_questions, 1, "the replacement must not ask for new targets");
            return entry.object_id;
        }
        let GameProgress::NeedsDecisionCtx(ctx) = progress else { panic!("{progress:?}"); };
        progress = apply_decision_context_with_dm(game, &mut queue, &mut state, &ctx, dm).unwrap();
    }
    panic!("cast did not finish");
}

fn receipts(game: &GameState, source: ObjectId) -> Vec<(DamageTarget, u32)> {
    game.turn_store.turn_history.event_records.iter()
        .chain(game.turn_store.turn_history.staged_event_records.iter())
        .filter_map(|record| record.event.downcast::<DamageEvent>())
        .filter(|event| event.source == source)
        .map(|event| (event.target, event.amount)).collect()
}

fn resolve_one(game: &mut GameState, source: ObjectId, recipient: ObjectId, amount: u32, dm: &mut Choices) {
    let questions = dm.target_questions;
    resolve_stack_entry_with(game, dm).unwrap();
    assert_eq!(game.damage_on(recipient), amount);
    assert_eq!(receipts(game, source), vec![(DamageTarget::Object(recipient), amount)],
        "one completed occurrence with the original source and recipient");
    assert_eq!(dm.target_questions, questions);
    assert_eq!(game.player(A).unwrap().life, 20);
    assert_eq!(game.player(B).unwrap().life, 20);
}

#[test]
fn full_cards_keep_one_replacement_and_their_secondary_bodies_through_all_codecs() {
    for name in ADOPTED { for definition in definitions(name) {
        assert_eq!(
            terminal_punctuation_normalized(&ironsmith_text::canonical_compiled_lines(&definition).join("\n")),
            terminal_punctuation_normalized(expected_rules(name)),
            "independent full-body expectation: {name}",
        );
        let mana = match *name {
            "Roil Eruption" | "Burning Hands" => "{1}{R}",
            "Akoum Hellkite" => "{4}{R}{R}",
            _ => "{R}",
        };
        assert_eq!(definition.card.mana_cost.as_ref().unwrap().to_oracle(), mana);
        assert_eq!(definition.card.card_types, vec![match *name {
            "Akoum Hellkite" => CardType::Creature,
            "Roil Eruption" => CardType::Sorcery,
            _ => CardType::Instant,
        }]);
        assert_eq!(definition.card.supertypes, if *name == "Frost Bite" { vec![Supertype::Snow] } else { vec![] });
        assert_eq!(definition.card.subtypes, if *name == "Akoum Hellkite" { vec![Subtype::Dragon] } else { vec![] });
        assert_eq!(definition.card.power_toughness, if *name == "Akoum Hellkite" { Some(PowerToughness::fixed(4, 4)) } else { None });
        let program = if *name == "Akoum Hellkite" {
            assert!(ironsmith_text::canonical_compiled_lines(&definition).join("\n").contains("Flying"));
            definition.abilities.iter().find_map(|ability| match &ability.kind {
                ironsmith::ability::AbilityKind::Triggered(triggered) => Some(&triggered.effects),
                _ => None,
            }).unwrap()
        } else { definition.spell_effect.as_ref().unwrap() };
        assert_eq!(program.segments.len(), 1, "{name}");
        assert_eq!(program.segments[0].self_replacements.len(), 1, "{name}");
        assert!(ironsmith_text::canonical_compiled_lines(&definition).join("\n").contains("instead"));
        if matches!(*name, "Burst Lightning" | "Roil Eruption" | "Shivan Fire") {
            assert_eq!(definition.optional_costs.len(), 1);
            assert_eq!(definition.optional_costs[0].kind, ironsmith_core::OptionalCostKind::Kicker);
            assert_eq!(definition.optional_costs[0].cost.mana_cost().unwrap().to_oracle(), if *name == "Roil Eruption" { "{5}" } else { "{4}" });
            assert!(!definition.optional_costs[0].cost.has_non_mana_costs());
            assert!(!definition.optional_costs[0].repeatable);
            assert!(!definition.optional_costs[0].returns_to_hand);
        }
        if *name == "Voltage Surge" {
            assert_eq!(definition.optional_costs.len(), 1);
            assert_eq!(definition.optional_costs[0].kind, ironsmith_core::OptionalCostKind::Additional);
            assert!(definition.optional_costs[0].cost.mana_cost().is_none());
            assert_eq!(definition.optional_costs[0].cost.non_mana_costs().count(), 1);
            assert_eq!(definition.optional_costs[0].cost.display().to_ascii_lowercase(), "sacrifice an artifact");
            assert!(!definition.optional_costs[0].repeatable);
            assert!(!definition.optional_costs[0].returns_to_hand);
        }
    }}
}

#[test]
fn kicker_replaces_the_amount_after_the_complete_printed_cost_is_paid() {
    for (name, ordinary, kicked) in [("Burst Lightning", 2, 4), ("Roil Eruption", 3, 5), ("Shivan Fire", 2, 4)] {
        for definition in definitions(name) { for pay in [false, true] {
            let mut game = game();
            let target = permanent(&mut game, B, CardType::Creature, false);
            let mut dm = Choices { targets: vec![Target::Object(target)], optional: pay, ..Default::default() };
            let source = cast(&mut game, &definition, &mut dm);
            assert_eq!(game.stack.last().unwrap().optional_costs_paid.was_kicked(), pay);
            resolve_one(&mut game, source, target, if pay { kicked } else { ordinary }, &mut dm);
        }}
    }
}

#[test]
fn frost_bite_rechecks_its_controllers_snow_population_at_resolution() {
    for definition in definitions("Frost Bite") { for rises in [false, true] {
        let mut game = game();
        let target = permanent(&mut game, B, CardType::Creature, false);
        for _ in 0..3 { permanent(&mut game, B, CardType::Land, true); }
        let mut snow = vec![];
        for _ in 0..2 { snow.push(permanent(&mut game, A, CardType::Land, true)); }
        if !rises { snow.push(permanent(&mut game, A, CardType::Land, true)); }
        let mut dm = Choices { targets: vec![Target::Object(target)], ..Default::default() };
        let source = cast(&mut game, &definition, &mut dm);
        if rises { permanent(&mut game, A, CardType::Artifact, true); }
        else { game.move_object_by_effect(snow[2], Zone::Graveyard).unwrap(); }
        resolve_one(&mut game, source, target, if rises { 3 } else { 2 }, &mut dm);
    }}
}

#[test]
fn burning_hands_reads_the_original_targets_current_color() {
    for definition in definitions("Burning Hands") { for becomes_green in [false, true] {
        let mut game = game();
        let target = permanent(&mut game, B, CardType::Creature, false);
        let decoy = permanent(&mut game, B, CardType::Creature, false);
        change(&mut game, decoy, Modification::SetColors(ColorSet::GREEN));
        if !becomes_green { change(&mut game, target, Modification::SetColors(ColorSet::GREEN)); }
        let mut dm = Choices { targets: vec![Target::Object(target)], ..Default::default() };
        let source = cast(&mut game, &definition, &mut dm);
        change(&mut game, target, Modification::SetColors(if becomes_green { ColorSet::GREEN } else { ColorSet::BLUE }));
        resolve_one(&mut game, source, target, if becomes_green { 6 } else { 2 }, &mut dm);
        assert_eq!(game.damage_on(decoy), 0);
    }}
}

#[test]
fn voltage_surge_keeps_its_sacrifice_cost_separate_from_the_damage_source_and_recipient() {
    for definition in definitions("Voltage Surge") { for pay in [false, true] {
        let mut game = game();
        let target = permanent(&mut game, B, CardType::Creature, false);
        let artifact = permanent(&mut game, A, CardType::Artifact, false);
        let stable = game.object(artifact).unwrap().stable_id;
        let mut dm = Choices { targets: vec![Target::Object(target)], optional: pay,
            sacrifice: pay.then_some(artifact), ..Default::default() };
        let source = cast(&mut game, &definition, &mut dm);
        let current_artifact = game.find_object_by_stable_id(stable).unwrap();
        assert_eq!(game.object(current_artifact).unwrap().zone, if pay { Zone::Graveyard } else { Zone::Battlefield });
        resolve_one(&mut game, source, target, if pay { 4 } else { 2 }, &mut dm);
    }}
}

#[test]
fn illegal_original_recipient_stops_both_damage_arms_without_retargeting() {
    for name in ["Burst Lightning", "Roil Eruption", "Shivan Fire", "Frost Bite", "Burning Hands", "Voltage Surge"] {
        for definition in definitions(name) {
            let mut game = game();
            let target = permanent(&mut game, B, CardType::Creature, false);
            let decoy = permanent(&mut game, B, CardType::Creature, false);
            let mut dm = Choices { targets: vec![Target::Object(target)],
                optional: matches!(name, "Burst Lightning" | "Roil Eruption" | "Shivan Fire"), ..Default::default() };
            let source = cast(&mut game, &definition, &mut dm);
            game.move_object_by_effect(target, Zone::Graveyard).unwrap();
            resolve_stack_entry_with(&mut game, &mut dm).unwrap();
            assert!(receipts(&game, source).is_empty());
            assert_eq!(game.damage_on(decoy), 0);
            assert_eq!(dm.target_questions, 1);
        }
    }
}

#[test]
fn landfall_replacement_reads_the_triggering_land_currently_or_at_its_exact_departure() {
    for definition in definitions("Akoum Hellkite") {
        for (starts_mountain, becomes_mountain, leaves) in [(false, true, false), (true, false, false), (false, true, true), (true, false, true)] {
            let mut game = game();
            let source = game.create_object_from_definition(&definition, A, Zone::Battlefield);
            let target = permanent(&mut game, B, CardType::Creature, false);
            change(&mut game, target, Modification::SetSubtypes(vec![Subtype::Mountain]));
            let land = CardBuilder::new(CardId::new(), "Triggering land").card_types(vec![CardType::Land])
                .subtypes(vec![if starts_mountain { Subtype::Mountain } else { Subtype::Island }]).build();
            let in_hand = game.create_object_from_card(&land, A, Zone::Hand);
            let land = game.move_object_by_effect(in_hand, Zone::Battlefield).unwrap();
            let mut queue = TriggerQueue::new();
            drain_pending_trigger_events(&mut game, &mut queue);
            queue.entries.retain(|entry| entry.source == source);
            assert_eq!(queue.entries.len(), 1);
            let mut dm = Choices { targets: vec![Target::Object(target)], ..Default::default() };
            put_triggers_on_stack_with_dm(&mut game, &mut queue, &mut dm).unwrap();
            assert_eq!(game.stack.last().unwrap().targets, dm.targets);
            change(&mut game, land, Modification::SetSubtypes(vec![if becomes_mountain { Subtype::Mountain } else { Subtype::Island }]));
            if leaves { game.move_object_by_effect(land, Zone::Graveyard).unwrap(); }
            resolve_one(&mut game, source, target, if becomes_mountain { 2 } else { 1 }, &mut dm);
        }
    }
}

#[test]
fn x_binding_and_partial_target_legality_remain_owned_by_the_original_declaration() {
    let text = "Mana cost: {X}{R}\nType: Instant\nThis spell deals X damage to two target creatures. If you control an artifact, it deals X plus 2 damage instead.";
    for definition in definitions_text("Bounded amount witness", text) { for illegal_count in 0..=2 {
        let mut game = game();
        permanent(&mut game, A, CardType::Artifact, false);
        let targets = [permanent(&mut game, B, CardType::Creature, false), permanent(&mut game, B, CardType::Creature, false)];
        let source = game.create_object_from_definition(&definition, A, Zone::Stack);
        let requirements = extract_target_requirements_from_program_with_modes(&game, definition.spell_effect.as_ref().unwrap(), A, Some(source), None);
        assert_eq!(requirements.len(), 1);
        assert_eq!(requirements[0].min_targets, 2);
        game.push_to_stack(StackEntry::new(source, A).with_x(3).with_targets(targets.map(Target::Object).to_vec())
            .with_target_assignments(vec![TargetAssignment { spec: requirements[0].spec.clone(), range: 0..2 }]));
        for target in targets.iter().take(illegal_count) { game.move_object_by_effect(*target, Zone::Graveyard).unwrap(); }
        resolve_stack_entry_with(&mut game, &mut Choices::default()).unwrap();
        let mut actual = receipts(&game, source);
        let mut expected = targets.iter().skip(illegal_count).map(|id| (DamageTarget::Object(*id), 5)).collect::<Vec<_>>();
        actual.sort_by_key(|entry| format!("{:?}", entry.0));
        expected.sort_by_key(|entry| format!("{:?}", entry.0));
        assert_eq!(actual, expected);
        for target in targets.iter().skip(illegal_count) { assert_eq!(game.damage_on(*target), 5); }
    }}
}

#[test]
fn distinct_unimplemented_condition_owners_remain_held() {
    for name in ["Flame Discharge", "Surtland Flinger", "Slaying Fire", "Summary Judgment"] {
        let text = card_text(name);
        assert!(compile_to_runtime_definition(name, &text, false).is_err(), "held direct route: {name}");
        assert!(compile_to_artifact(name, &text, false).is_err(), "held artifact route: {name}");
    }
}
