//! Other miscellaneous events.

mod became_monstrous;
mod card_discarded;
mod card_drawn;
mod card_revealed;
mod chapter_ability_resolved;
mod coin_flipped;
mod control_changed;
mod converted;
mod counter_placed;
mod day_night_changed;
mod die_rolled;
pub(crate) use die_rolled::bind_die_roll_batch_results;
mod gift_given;
pub(crate) mod keyword_action;
mod land_played;
mod markers_changed;
mod mutated;
mod object_became_unattached;
mod object_became_attached;
pub use object_became_attached::ObjectBecameAttachedEvent;
mod permanent_phased_out;
mod card_milled;
pub use card_milled::CardMilledEvent;
mod permanent_phased_in;
pub use permanent_phased_in::PermanentPhasedInEvent;
mod permanent_tapped;
mod permanent_untapped;
pub(crate) mod player_loses_game;
mod players_finished_voting;
mod search_library;
mod shuffle_library;
mod spell_countered;
mod state_trigger;
mod transformed;
mod turned_face_up;

pub use became_monstrous::BecameMonstrousEvent;
pub use card_discarded::{CardDiscardedEvent, DiscardedCardDestination};
pub use card_drawn::{CardsDrawnEvent, DrawnMiracleInstance, DrawnMiraclePrice, MiracleDrawDecision, MiracleInstanceIdentity, RevealedMiracle};
pub(crate) use card_drawn::MiracleDrawOpportunity;
pub use card_revealed::{CardRevealedEvent, FirstDrawRevealOccurrence};
pub use chapter_ability_resolved::ChapterAbilityResolvedEvent;
pub use coin_flipped::CoinFlippedEvent;
pub use control_changed::ControlChangedEvent;
pub use converted::ConvertedEvent;
pub use counter_placed::CounterPlacedEvent;
pub use day_night_changed::DayNightChangedEvent;
pub use die_rolled::DieRolledEvent;
pub use gift_given::GiftGivenEvent;
pub use keyword_action::{KeywordActionEvent, KeywordActionKind, WouldKeywordActionMatcher};
pub use land_played::LandPlayedEvent;
pub use markers_changed::{MarkerChangeType, MarkersChangedEvent};
pub use mutated::MutatedEvent;
pub use object_became_unattached::ObjectBecameUnattachedEvent;
pub use permanent_phased_out::PermanentPhasedOutEvent;
pub use permanent_tapped::PermanentTappedEvent;
pub(crate) use permanent_tapped::{before_tap_state_snapshots, bind_before_tap_state_snapshots, group_tap_state_events};
pub use permanent_untapped::PermanentUntappedEvent;
pub use player_loses_game::{PlayerLosesGameEvent, WouldLoseGameMatcher};
pub use players_finished_voting::{PlayerVote, PlayersFinishedVotingEvent};
pub(crate) use players_finished_voting::vote_event_players_are_opponents;
pub use search_library::SearchLibraryEvent;
pub use shuffle_library::ShuffleLibraryEvent;
pub use spell_countered::SpellCounteredEvent;
pub use state_trigger::StateTriggerEvent;
pub use transformed::TransformedEvent;
pub use turned_face_up::TurnedFaceUpEvent;
mod lifecycle_snapshot;
pub(crate) use lifecycle_snapshot::{freeze_completed_lifecycle_events, retain_departed_lifecycle_snapshots};

mod monarch_changed;
pub use monarch_changed::MonarchChangedEvent;
