import test from "node:test";
import assert from "node:assert/strict";
import { chromium } from "playwright";
import { createServer } from "vite";

test("mana sources stay active during payment, replace inspection, and yield to nested decisions", async () => {
  const vite = await createServer({server:{host:"127.0.0.1",port:0},logLevel:"silent"});
  await vite.listen();
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({viewport:{width:1100,height:800}});
    const errors = [];
    page.on("pageerror",error=>errors.push(error.message));
    await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/tests/mana-payment-interactions.html`, {waitUntil:"domcontentloaded"});
    const mountain = page.locator('.battlefield-row-card[data-object-id="1"]');
    await mountain.waitFor();
    await mountain.hover();
    const popover = page.getByRole("dialog",{name:"Activate mana ability"});
    assert.equal(await popover.count(),0);
    assert.equal(await page.locator('.floating-card-preview[data-visible="true"]').count(),0);
    assert.equal(await page.locator("[data-hover]").textContent(),"none");
    assert.equal(await page.locator("[data-inspected]").textContent(),"none");
    await mountain.click();
    assert.deepEqual(JSON.parse(await page.locator("[data-command]").textContent()),{type:"mana_payment",response:{action:"activate",source_id:"1",ability_index:0}});
    assert.equal(await page.locator("[data-decision]").textContent(),"mana_payment");
    await popover.waitFor({state:"hidden"});
    await page.getByRole("button", {name:"Toggle busy"}).hover();
    await mountain.hover();
    await page.waitForFunction(() => document.querySelector("[data-hover]").textContent === "1");
    assert.equal(await page.locator("[data-hover]").textContent(),"1");
    const prism = page.locator('.battlefield-row-card[data-object-id="2"]');
    await prism.hover();
    await popover.waitFor();
    assert.equal(await popover.locator("[data-action-row]").count(),2);
    await popover.locator("[data-action-row]").nth(1).hover();
    await page.waitForTimeout(300);
    const rect = await popover.boundingBox();
    await page.screenshot({path:"/tmp/mana-payment-popover.png",clip:{x:rect.x-12,y:rect.y-12,width:rect.width+24,height:rect.height+40}});
    await popover.locator("[data-action-row]").nth(1).click();
    await page.waitForFunction(() => document.querySelector("[data-decision]").textContent === "select_objects");
    await popover.waitFor({state:"hidden"});
    // Nested choices restore the pinned inspector; unpin it before testing the board.
    await page.getByRole("button", {name:"Unpin inspector"}).click();
    await prism.hover();
    assert.equal(await page.locator("[data-hover]").textContent(),"2");
    await page.getByRole("button",{name:"Resume payment"}).click();
    await prism.hover();
    await popover.waitFor();
    assert.equal(await page.locator("[data-inspected]").textContent(),"none");
    await page.keyboard.press("Escape");
    await popover.waitFor({state:"hidden"});
    await page.getByRole("button",{name:"Switch payer"}).click();
    await prism.hover();
    assert.equal(await popover.count(),0);
    assert.equal(await page.locator("[data-hover]").textContent(),"2");
    await page.getByRole("button",{name:"Switch payer"}).click();
    await page.getByRole("button",{name:"Filter Prism to one ability"}).click();
    await prism.click();
    await page.waitForFunction(() => document.querySelector("[data-decision]").textContent === "select_objects");
    assert.equal(await popover.count(),0);
    assert.deepEqual(JSON.parse(await page.locator("[data-command]").textContent()),{type:"mana_payment",response:{action:"activate",source_id:"2",ability_index:1}});
    assert.deepEqual(errors,[]);
  } finally { await browser.close(); await vite.close(); }
});
