use crate::tag::TagKeyWalk;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, TagKeyWalk)]
pub enum KeywordActionKind {
    Sticker,
    Amass,
    AssembleContraption,
    ArtSticker,
    AbilitySticker,
    PowerToughnessSticker,
    Bolster,
    Blight,
    Waterbend,
    Clash,
    CommitCrime,
    ClaimAttractionPrize,
    Craft,
    Crew,
    Cycle,
    CumulativeUpkeepNotPaid,
    Convoke,
    Discover,
    CompleteDungeon,
    /// A player moved their venture marker (CR 701.49).
    VentureIntoDungeon,
    Evolve,
    Earthbend,
    Enlist,
    Explore,
    Exploit,
    Exert,
    Expend,
    Fateseal,
    Firebend,
    Fight,
    Forage,
    Harness,
    Heal,
    Improvise,
    Incubate,
    Investigate,
    Learn,
    Manifest,
    ManifestDread,
    Cloak,
    OpenAttraction,
    NameSticker,
    Populate,
    Plot,
    RingTemptsYou,
    Renown,
    Saddle,
    Planeswalk,
    ChaosEnsues,
    EncounterPhenomenon,
    SetSchemeInMotion,
    AbandonScheme,
    Connive,
    Proliferate,
    Support,
    Scry,
    Surveil,
    Train,
    UnlockDoor,
    /// A player fully unlocks a Room (CR 709.5i): it had one unlocked
    /// designation and gets the other.
    FullyUnlockRoom,
    /// This Class's level becomes N (CR 716.2a); the event amount is N.
    GainClassLevel,
    VisitAttraction,
    Vote,
    Airbend,
    /// A player takes the initiative (CR 725.2).
    TakeInitiative,
    /// A creature's mentor ability put a +1/+1 counter on a creature
    /// (CR 702.134): that creature "mentors" the creature that got the
    /// counter.
    Mentor,
    /// A permanent becomes saddled (CR 702.171b): the event's source is the
    /// permanent that became saddled, not a creature that saddled it.
    BecomeSaddled,
}

impl KeywordActionKind {
    pub fn is_sticker(self) -> bool {
        matches!(
            self,
            Self::Sticker
                | Self::ArtSticker
                | Self::AbilitySticker
                | Self::PowerToughnessSticker
                | Self::NameSticker
        )
    }

    /// Whether an authored action category matches the action that was
    /// actually performed. `Sticker` is the umbrella action used by rules
    /// text that triggers from any kind of sticker.
    pub fn matches_performed_action(self, performed: Self) -> bool {
        self == performed || (self == Self::Sticker && performed.is_sticker())
    }

    pub fn from_trigger_word(word: &str) -> Option<Self> {
        match word {
            "sticker" | "stickers" | "stickered" => Some(Self::Sticker),
            "amass" | "amasses" | "amassed" | "amassing" => Some(Self::Amass),
            "assemble" | "assembles" | "assembled" | "assembling" => {
                Some(Self::AssembleContraption)
            }
            "bolster" | "bolsters" | "bolstered" | "bolstering" => Some(Self::Bolster),
            "blight" | "blights" | "blighted" | "blighting" => Some(Self::Blight),
            "waterbend" | "waterbends" | "waterbent" | "waterbending" => Some(Self::Waterbend),
            "clash" | "clashes" | "clashed" | "clashing" => Some(Self::Clash),
            "crime" | "crimes" => Some(Self::CommitCrime),
            "craft" | "crafts" | "crafted" | "crafting" => Some(Self::Craft),
            "crew" | "crews" | "crewed" | "crewing" => Some(Self::Crew),
            "saddle" | "saddles" | "saddled" | "saddling" => Some(Self::Saddle),
            "cycle" | "cycles" | "cycled" => Some(Self::Cycle),
            "cycling" => Some(Self::Cycle),
            "convoke" | "convokes" | "convoked" => Some(Self::Convoke),
            "discover" | "discovers" | "discovered" | "discovering" => Some(Self::Discover),
            "complete" | "completes" | "completed" | "completing" => Some(Self::CompleteDungeon),
            "evolve" | "evolves" | "evolved" | "evolving" => Some(Self::Evolve),
            "airbend" | "airbends" | "airbent" | "airbending" => Some(Self::Airbend),
            "earthbend" | "earthbends" => Some(Self::Earthbend),
            "enlist" | "enlists" | "enlisted" | "enlisting" => Some(Self::Enlist),
            "explore" | "explores" | "explored" | "exploring" => Some(Self::Explore),
            "exploit" | "exploits" | "exploited" | "exploiting" => Some(Self::Exploit),
            "exert" | "exerts" | "exerted" | "exerting" => Some(Self::Exert),
            "expend" | "expends" | "expended" => Some(Self::Expend),
            "fateseal" | "fateseals" | "fatesealed" | "fatesealing" => Some(Self::Fateseal),
            "firebend" | "firebends" | "firebent" | "firebending" => Some(Self::Firebend),
            "fight" | "fights" | "fought" | "fighting" => Some(Self::Fight),
            "forage" | "forages" | "foraged" | "foraging" => Some(Self::Forage),
            "harness" | "harnesses" | "harnessed" | "harnessing" => Some(Self::Harness),
            "heal" | "heals" | "healed" | "healing" => Some(Self::Heal),
            "improvise" | "improvises" | "improvised" => Some(Self::Improvise),
            "incubate" | "incubates" | "incubated" | "incubating" => Some(Self::Incubate),
            "investigate" | "investigates" => Some(Self::Investigate),
            "learn" | "learns" | "learned" | "learning" => Some(Self::Learn),
            "manifest" | "manifests" | "manifested" | "manifesting" => Some(Self::Manifest),
            "cloak" | "cloaks" | "cloaked" | "cloaking" => Some(Self::Cloak),
            "populate" | "populates" | "populated" | "populating" => Some(Self::Populate),
            "planeswalk" | "planeswalks" | "planeswalked" | "planeswalking" => {
                Some(Self::Planeswalk)
            }
            "encounter" | "encounters" | "encountered" | "encountering" => {
                Some(Self::EncounterPhenomenon)
            }
            "abandon" | "abandons" | "abandoned" | "abandoning" => Some(Self::AbandonScheme),
            "plot" | "plots" | "plotted" | "plotting" => Some(Self::Plot),
            "renown" | "renowned" => Some(Self::Renown),
            "connive" | "connives" | "connived" => Some(Self::Connive),
            "proliferate" | "proliferates" => Some(Self::Proliferate),
            "support" | "supports" | "supported" | "supporting" => Some(Self::Support),
            "scry" | "scries" => Some(Self::Scry),
            "surveil" | "surveils" => Some(Self::Surveil),
            "train" | "trains" | "trained" | "training" => Some(Self::Train),
            "unlock" | "unlocks" | "unlocked" | "unlocking" => Some(Self::UnlockDoor),
            "visit" | "visits" | "visited" | "visiting" => Some(Self::VisitAttraction),
            "vote" | "votes" | "voting" => Some(Self::Vote),
            "mentors" => Some(Self::Mentor),
            _ => None,
        }
    }

    pub fn infinitive(self) -> &'static str {
        match self {
            Self::Sticker => "put a sticker",
            Self::Amass => "amass",
            Self::AssembleContraption => "assemble a Contraption",
            Self::ArtSticker => "put an art sticker",
            Self::AbilitySticker => "put an ability sticker",
            Self::PowerToughnessSticker => "put a power and toughness sticker",
            Self::Bolster => "bolster",
            Self::Blight => "blight",
            Self::Waterbend => "waterbend",
            Self::Clash => "clash",
            Self::CommitCrime => "commit a crime",
            Self::ClaimAttractionPrize => "claim the prize of an Attraction",
            Self::Craft => "craft",
            Self::Crew => "crew",
            Self::Cycle => "cycle",
            Self::CumulativeUpkeepNotPaid => "not pay cumulative upkeep",
            Self::Convoke => "convoke",
            Self::Discover => "discover",
            Self::CompleteDungeon => "complete a dungeon",
            Self::VentureIntoDungeon => "venture into the dungeon",
            Self::Evolve => "evolve",
            Self::Airbend => "airbend",
            Self::Earthbend => "earthbend",
            Self::Enlist => "enlist",
            Self::Explore => "explore",
            Self::Exploit => "exploit",
            Self::Exert => "exert",
            Self::Expend => "expend",
            Self::Fateseal => "fateseal",
            Self::Firebend => "firebend",
            Self::Fight => "fight",
            Self::Forage => "forage",
            Self::Harness => "harness",
            Self::Heal => "heal damage",
            Self::Improvise => "improvise",
            Self::Incubate => "incubate",
            Self::Investigate => "investigate",
            Self::Learn => "learn",
            Self::Manifest => "manifest",
            Self::ManifestDread => "manifest dread",
            Self::Cloak => "cloak",
            Self::OpenAttraction => "open an Attraction",
            Self::Populate => "populate",
            Self::Planeswalk => "planeswalk",
            Self::ChaosEnsues => "chaos ensues",
            Self::EncounterPhenomenon => "encounter a phenomenon",
            Self::SetSchemeInMotion => "set a scheme in motion",
            Self::AbandonScheme => "abandon a scheme",
            Self::Plot => "plot",
            Self::NameSticker => "put a name sticker",
            Self::RingTemptsYou => "have the Ring tempt you",
            Self::Renown => "become renowned",
            Self::Saddle => "saddle",
            Self::Connive => "connive",
            Self::Proliferate => "proliferate",
            Self::Support => "support",
            Self::Scry => "scry",
            Self::Surveil => "surveil",
            Self::Train => "train",
            Self::UnlockDoor => "unlock this door",
            Self::FullyUnlockRoom => "fully unlock a Room",
            Self::GainClassLevel => "level up this Class",
            Self::VisitAttraction => "visit an Attraction",
            Self::Vote => "vote",
            Self::TakeInitiative => "take the initiative",
            Self::Mentor => "mentor",
            Self::BecomeSaddled => "become saddled",
        }
    }

    pub fn third_person(self) -> &'static str {
        match self {
            Self::Sticker => "puts a sticker",
            Self::Amass => "amasses",
            Self::AssembleContraption => "assembles a Contraption",
            Self::ArtSticker => "puts an art sticker",
            Self::AbilitySticker => "puts an ability sticker",
            Self::PowerToughnessSticker => "puts a power and toughness sticker",
            Self::Bolster => "bolsters",
            Self::Blight => "blights",
            Self::Waterbend => "waterbends",
            Self::Clash => "clashes",
            Self::CommitCrime => "commits a crime",
            Self::ClaimAttractionPrize => "claims the prize of an Attraction",
            Self::Craft => "crafts",
            Self::Crew => "crews",
            Self::Cycle => "cycles",
            Self::CumulativeUpkeepNotPaid => "doesn't pay cumulative upkeep",
            Self::Convoke => "convokes",
            Self::Discover => "discovers",
            Self::CompleteDungeon => "completes a dungeon",
            Self::VentureIntoDungeon => "ventures into the dungeon",
            Self::Evolve => "evolves",
            Self::Airbend => "airbends",
            Self::Earthbend => "earthbends",
            Self::Enlist => "enlists",
            Self::Explore => "explores",
            Self::Exploit => "exploits",
            Self::Exert => "exerts",
            Self::Expend => "expends",
            Self::Fateseal => "fateseals",
            Self::Firebend => "firebends",
            Self::Fight => "fights",
            Self::Forage => "forages",
            Self::Harness => "harnesses",
            Self::Heal => "heals damage",
            Self::Improvise => "improvises",
            Self::Incubate => "incubates",
            Self::Investigate => "investigates",
            Self::Learn => "learns",
            Self::Manifest => "manifests",
            Self::ManifestDread => "manifests dread",
            Self::Cloak => "cloaks",
            Self::OpenAttraction => "opens an Attraction",
            Self::Populate => "populates",
            Self::Planeswalk => "planeswalks",
            Self::ChaosEnsues => "chaos ensues",
            Self::EncounterPhenomenon => "encounters a phenomenon",
            Self::SetSchemeInMotion => "sets a scheme in motion",
            Self::AbandonScheme => "abandons a scheme",
            Self::Plot => "plots",
            Self::NameSticker => "puts a name sticker",
            Self::RingTemptsYou => "has the Ring tempt them",
            Self::Renown => "becomes renowned",
            Self::Saddle => "saddles",
            Self::Connive => "connives",
            Self::Proliferate => "proliferates",
            Self::Support => "supports",
            Self::Scry => "scries",
            Self::Surveil => "surveils",
            Self::Train => "trains",
            Self::UnlockDoor => "unlocks this door",
            Self::FullyUnlockRoom => "fully unlocks a Room",
            Self::GainClassLevel => "levels up this Class",
            Self::VisitAttraction => "visits an Attraction",
            Self::Vote => "votes",
            Self::TakeInitiative => "takes the initiative",
            Self::Mentor => "mentors",
            Self::BecomeSaddled => "becomes saddled",
        }
    }
}
