#!/usr/bin/env python3
"""Generate Rust source with parser-backed card registry entries from cards.json."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Dict, Tuple

from stream_scryfall_blocks import build_block, iter_json_array


ROOT = Path(__file__).resolve().parents[1]
CARDS_JSON = ROOT / "cards.json"
OUT_FILE = ROOT / "src" / "cards" / "generated_registry.rs"


def rust_raw_literal(value: str) -> str:
    """Return a Rust string literal (raw when possible)."""
    for hashes in range(0, 12):
        marks = "#" * hashes
        end = f'"{marks}'
        if end not in value:
            return f'r{marks}"{value}"{marks}'
    return json.dumps(value)


def load_excluded_name_keys() -> set[str]:
    raw_path = os.environ.get("IRONSMITH_GENERATED_REGISTRY_SKIP_NAMES_FILE", "").strip()
    if not raw_path:
        return set()

    path = Path(raw_path)
    if not path.exists():
        print(f"[generate_baked_registry] skip-list file not found: {path}")
        return set()

    excluded: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        name = line.strip()
        if name:
            excluded.add(name.casefold())
    return excluded


def collect_unique_blocks(excluded_name_keys: set[str]) -> Dict[str, Tuple[str, str]]:
    unique: Dict[str, Tuple[str, str]] = {}
    for card in iter_json_array(CARDS_JSON):
        block = build_block(card)
        if not block:
            continue
        lines = block.splitlines()
        first_line = lines[0] if lines else ""
        if not first_line.startswith("Name: "):
            continue
        name = first_line.removeprefix("Name: ").strip()
        if not name:
            continue
        # Keep metadata + oracle text only. Name is provided by the Rust builder.
        # Leaving "Name:" inside the parse input causes strict parser failures.
        parse_block = "\n".join(lines[1:]).strip()
        key = name.casefold()
        if key in excluded_name_keys:
            continue
        if key not in unique:
            unique[key] = (name, parse_block)
    return unique


def write_generated_source(cards: Dict[str, Tuple[str, str]], output_path: Path) -> None:
    ordered = sorted(cards.values(), key=lambda pair: pair[0].casefold())

    lines = []
    lines.append("// @generated by scripts/generate_baked_registry.py")
    lines.append("// Do not edit manually.")
    lines.append("")
    lines.append("use super::{CardDefinition, CardDefinitionBuilder, CardRegistry};")
    lines.append("use crate::ids::CardId;")
    lines.append("use std::sync::OnceLock;")
    lines.append("")
    lines.append(f"pub const GENERATED_PARSER_CARD_SOURCE_COUNT: usize = {len(ordered)};")
    lines.append("")
    lines.append("fn parse_generated_card(cards: &mut Vec<CardDefinition>, name: &str, block: &str) {")
    lines.append("    let builder = CardDefinitionBuilder::new(CardId::new(), name);")
    lines.append("    if let Ok(definition) = builder.parse_text(block.to_string()) {")
    lines.append("        if super::generated_definition_is_supported(&definition) {")
    lines.append("            cards.push(definition);")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("fn parsed_generated_cards() -> &'static Vec<CardDefinition> {")
    lines.append("    static PARSED: OnceLock<Vec<CardDefinition>> = OnceLock::new();")
    lines.append("    PARSED.get_or_init(|| {")
    lines.append("        let mut cards = Vec::new();")
    for name, block in ordered:
        name_lit = rust_raw_literal(name)
        block_lit = rust_raw_literal(block)
        lines.append(f"        parse_generated_card(&mut cards, {name_lit}, {block_lit});")
    lines.append("        cards")
    lines.append("    })")
    lines.append("}")
    lines.append("")
    lines.append("pub fn register_generated_parser_cards(registry: &mut CardRegistry) {")
    lines.append("    for definition in parsed_generated_cards() {")
    lines.append("        if registry.get(definition.card.name.as_str()).is_none() {")
    lines.append("            registry.register(definition.clone());")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate baked parser registry source from cards.json"
    )
    parser.add_argument(
        "--out",
        dest="out",
        default=str(OUT_FILE),
        help="Output Rust source file path",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_path = Path(args.out)
    excluded_name_keys = load_excluded_name_keys()
    cards = collect_unique_blocks(excluded_name_keys)
    write_generated_source(cards, output_path)
    print(
        f"wrote {output_path} with {len(cards)} source cards "
        f"(excluded by threshold: {len(excluded_name_keys)})"
    )


if __name__ == "__main__":
    main()
