use super::*;

/// Whether a one-word alias is a rules word rather than a name. `alias_tokens`
/// is the alias's own token, from the name it was read out of.
pub(super) fn is_reserved_short_alias(alias: &str, alias_tokens: &[OwnedLexToken]) -> bool {
    let lower = alias.to_ascii_lowercase();
    if super::super::super::keyword_dispatch::parse_keyword_dispatch_hint_tokens(alias_tokens)
        .is_some()
        || super::super::super::line_families::parse_simple_document_line(alias_tokens).is_some()
    {
        return true;
    }
    if super::super::super::sentence_markers::parse_keyword_marker_tokens(alias_tokens).is_some() {
        return true;
    }
    if matches!(
        lower.as_str(),
        "prototype" | "dredge" | "enchanted" | "equipped" | "command" | "flashback"
            | "cast" | "casts" | "play" | "plays" | "protection" | "roll" | "rolls"
            // "Venture into the dungeon" (Dungeon Map, Dungeon Descent): the
            // dungeon is a game object (CR 309), never the source's alias.
            | "dungeon"
    ) {
        return true;
    }
    // A characteristic word (card type, supertype, color) is never a short
    // card-name alias.
    if super::super::super::leaf::parse_leaf_card_type_complete(&lower).is_ok()
        || super::super::super::leaf::parse_leaf_supertype_complete(&lower).is_ok()
        || super::super::super::leaf::parse_leaf_color_complete(&lower).is_ok()
    {
        return true;
    }
    if let Ok(subtype) = super::super::super::leaf::parse_leaf_subtype_flexible_complete(&lower) {
        // Planeswalker first names are both legitimate short source names and
        // planeswalker subtypes. Other subtype words in rules text are much
        // more likely to be characteristic selectors (for example,
        // "Skeleton or Pirate") than abbreviated card names.
        return !subtype.is_planeswalker_subtype();
    }
    matches!(
        lower.as_str(),
        "a" | "an"
            | "and" | "or" | "but" | "then" | "else"
            | "the"
            | "one"
            | "two"
            | "three"
            | "four"
            | "five"
            | "six"
            | "seven"
            | "eight"
            | "nine"
            | "ten"
            | "x"
            | "all"
            | "any"
            | "each"
            | "every"
            | "single"
            | "another"
            | "other"
            | "this"
            | "that"
            | "these"
            | "those"
            | "you"
            | "your"
            | "when"
            | "whenever"
            | "if"
            | "unless"
            | "then"
            | "also"
            | "at"
            | "for"
            | "from"
            | "out"
            | "until"
            | "during"
            | "turn"
            | "without"
            | "with"
            | "first"
            | "second"
            | "third"
            | "fourth"
            | "fifth"
            | "sixth"
            | "seventh"
            | "eighth"
            | "ninth"
            | "tenth"
            | "last"
            | "next"
            | "additional"
            | "alternative"
            | "target"
            | "targets"
            | "targeted"
            | "add"
            | "added"
            | "move"
            | "moved"
            | "deal"
            | "deals"
            | "dealt"
            | "damaged"
            | "draw"
            | "draws"
            | "drawn"
            | "counter"
            | "countered"
            | "double"
            | "doubles"
            | "doubled"
            | "destroy"
            | "destroyed"
            | "exile"
            | "untap"
            | "tapped"
            | "untapped"
            | "scry"
            | "discard"
            | "discarded"
            | "transform"
            | "transformed"
            | "regenerate"
            | "mill"
            | "milled"
            | "get"
            | "reveal"
            | "revealed"
            | "look"
            | "prevent"
            | "prevents"
            | "prevented"
            | "lose"
            | "lost"
            | "gain"
            | "gained"
            | "put"
            | "sacrifice"
            | "sacrificed"
            | "create"
            | "created"
            | "investigate"
            | "attach"
            | "attached"
            | "unattached"
            | "remove"
            | "removed"
            | "return"
            | "returned"
            | "exchange"
            | "become"
            | "became"
            | "switch"
            | "skip"
            | "surveil"
            | "shuffle"
            | "reorder"
            | "pay"
            | "paid"
            | "goad"
            | "goaded"
            | "exiled"
            | "blocked"
            | "blocking"
            | "attacking"
            | "top"
            | "bottom"
            | "same"
            | "different"
            | "villainous"
            | "chosen"
            | "named"
            | "counted"
            | "rounded"
            | "rest"
            | "source"
            | "color"
            | "copy"
            | "clash"
            | "coin"
            | "radiance"
            | "station"
            | "speed"
            | "historic"
            | "nonhistoric"
            | "power"
            | "toughness"
            | "mana"
            | "life"
            | "commander"
            | "player"
            | "opponent"
            | "creature"
            | "artifact"
            | "enchantment"
            | "land"
            | "spell"
            | "card"
            | "token"
            | "permanent"
            | "library"
            | "graveyard"
            | "hand"
            | "battlefield"
            | "controller"
            | "owner"
            | "planeswalker"
            | "battle"
            | "equipment"
            | "aura"
    ) || parse_keyword_ability_name_tokens(alias_tokens).is_some()
}
