/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmgame_free: (a: number, b: number) => void;
export const wasmgame_new: () => number;
export const wasmgame_reset: (a: number, b: any, c: number) => [number, number];
export const wasmgame_startMatch: (a: number, b: any) => [number, number, number];
export const wasmgame_snapshot: (a: number) => [number, number, number];
export const wasmgame_registrySize: (a: number) => number;
export const wasmgame_preloadRegistryStatus: (a: number) => [number, number, number];
export const wasmgame_preloadRegistryChunk: (a: number, b: number) => [number, number, number];
export const wasmgame_objectDetails: (a: number, b: bigint) => [number, number, number];
export const wasmgame_snapshotJson: (a: number) => [number, number, number, number];
export const wasmgame_autocompleteCardNames: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasmgame_setLife: (a: number, b: number, c: number) => [number, number];
export const wasmgame_addLifeDelta: (a: number, b: number, c: number) => [number, number];
export const wasmgame_drawCard: (a: number, b: number) => [number, number, number];
export const wasmgame_addCardToHand: (a: number, b: number, c: number, d: number) => [bigint, number, number];
export const wasmgame_addCardToZone: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [bigint, number, number];
export const wasmgame_drawOpeningHands: (a: number, b: number) => [number, number];
export const wasmgame_loadDemoDecks: (a: number) => [number, number];
export const wasmgame_loadDecks: (a: number, b: any) => [number, number, number];
export const wasmgame_cardLoadDiagnostics: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmgame_sampleLoadedDeckSeed: (a: number, b: number) => [number, number, number];
export const wasmgame_previewCustomCard: (a: number, b: any) => [number, number, number];
export const wasmgame_createCustomCard: (a: number, b: any) => [bigint, number, number];
export const wasmgame_advancePhase: (a: number) => [number, number];
export const wasmgame_setAutoCleanupDiscard: (a: number, b: number) => void;
export const wasmgame_setSemanticThreshold: (a: number, b: number) => void;
export const wasmgame_getSemanticThreshold: (a: number) => number;
export const wasmgame_getCardSemanticScore: (a: number, b: number, c: number) => number;
export const wasmgame_cardsMeetingThreshold: (a: number) => number;
export const wasmgame_switchPerspective: (a: number) => [number, number, number];
export const wasmgame_setPerspective: (a: number, b: number) => [number, number];
export const wasmgame_cancelDecision: (a: number) => [number, number, number];
export const wasmgame_dispatch: (a: number, b: any) => [number, number, number];
export const wasmgame_uiState: (a: number) => [number, number, number];
export const wasm_start: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
