//! Parallel composition facade for typed compiled-effect decoding.

use std::any::Any;

use serde_json::Value;

pub type ErasedPayload = Box<dyn Any + Send + Sync>;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EffectFamily {
    ZoneLibrary,
    Player,
    Resources,
    Permanent,
    Combat,
    StackEvent,
    CompositionAL,
    CompositionMZ,
}

pub fn family_for_kind(kind: &str) -> Option<EffectFamily> {
    match kind {
        "AdaptEffect" => Some(EffectFamily::CompositionAL),
        "AddManaEffect" => Some(EffectFamily::Resources),
        "AddManaFromCommanderColorIdentityEffect" => Some(EffectFamily::Resources),
        "AddManaOfAnyColorEffect" => Some(EffectFamily::Resources),
        "AddManaOfAnyOneColorEffect" => Some(EffectFamily::Resources),
        "AddManaOfChosenColorEffect" => Some(EffectFamily::Resources),
        "AddManaOfColorsAmongEffect" => Some(EffectFamily::Resources),
        "AddManaOfImprintedColorsEffect" => Some(EffectFamily::Resources),
        "AddManaOfLandProducedTypesEffect" => Some(EffectFamily::Resources),
        "AddOneManaOfAnyColorAmongEffect" => Some(EffectFamily::Resources),
        "AddScaledManaEffect" => Some(EffectFamily::Resources),
        "AdditionalLandPlaysEffect" => Some(EffectFamily::Player),
        "AdditionalPhasesEffect" => Some(EffectFamily::Player),
        "AmassEffect" => Some(EffectFamily::Permanent),
        "AmplifyEffect" => Some(EffectFamily::CompositionAL),
        "ApplyContinuousEffect" => Some(EffectFamily::Permanent),
        "AscendEffect" => Some(EffectFamily::Player),
        "AssignNoCombatDamageEffect" => Some(EffectFamily::Combat),
        "AttachObjectsEffect" => Some(EffectFamily::Permanent),
        "AttachToEffect" => Some(EffectFamily::Permanent),
        "AuraSwapEffect" => Some(EffectFamily::CompositionAL),
        "BackupEffect" => Some(EffectFamily::CompositionAL),
        "BecomeBasicLandTypeChoiceEffect" => Some(EffectFamily::Permanent),
        "BecomeColorChoiceEffect" => Some(EffectFamily::Permanent),
        "BecomeCreatureTypeChoiceEffect" => Some(EffectFamily::Permanent),
        "BecomeMonarchEffect" => Some(EffectFamily::Player),
        "BecomeSaddledUntilEotEffect" => Some(EffectFamily::Permanent),
        "BeholdEffect" => Some(EffectFamily::CompositionAL),
        "BidLifeEffect" => Some(EffectFamily::CompositionAL),
        "BolsterEffect" => Some(EffectFamily::CompositionAL),
        "CantEffect" => Some(EffectFamily::StackEvent),
        "CastSourceEffect" => Some(EffectFamily::Player),
        "CastTaggedEffect" => Some(EffectFamily::Player),
        "ChooseCardNameEffect" => Some(EffectFamily::Player),
        "ChooseCardTypeEffect" => Some(EffectFamily::Player),
        "ChooseColorEffect" => Some(EffectFamily::Player),
        "ChooseCreatureTypeEffect" => Some(EffectFamily::Player),
        "ChooseLandTypeEffect" => Some(EffectFamily::Player),
        "ChooseModeEffect" => Some(EffectFamily::CompositionAL),
        "ChooseNamedOptionEffect" => Some(EffectFamily::Player),
        "ChooseNewTargetsEffect" => Some(EffectFamily::StackEvent),
        "ChooseObjectsEffect" => Some(EffectFamily::CompositionAL),
        "ChoosePlayerEffect" => Some(EffectFamily::Player),
        "ChooseSpellCastHistoryEffect" => Some(EffectFamily::CompositionAL),
        "CipherEffect" => Some(EffectFamily::CompositionAL),
        "ClashEffect" => Some(EffectFamily::ZoneLibrary),
        "ClearSuspectedEffect" => Some(EffectFamily::Permanent),
        "ConditionalEffect" => Some(EffectFamily::CompositionAL),
        "ConniveEffect" => Some(EffectFamily::ZoneLibrary),
        "ConspireCostEffect" => Some(EffectFamily::Permanent),
        "ConsultTopOfLibraryEffect" => Some(EffectFamily::ZoneLibrary),
        "ControlCombatChoicesThisTurnEffect" => Some(EffectFamily::Player),
        "ControlPlayerEffect" => Some(EffectFamily::Player),
        "ConvertEffect" => Some(EffectFamily::Permanent),
        "CopySpellEffect" => Some(EffectFamily::StackEvent),
        "CopySpellForEachTargetEffect" => Some(EffectFamily::StackEvent),
        "CounterEffect" => Some(EffectFamily::StackEvent),
        "CreateEmblemEffect" => Some(EffectFamily::Player),
        "CreateTokenCopyEffect" => Some(EffectFamily::Permanent),
        "CreateTokenEffect" => Some(EffectFamily::Permanent),
        "CrewCostEffect" => Some(EffectFamily::Permanent),
        "CumulativeUpkeepEffect" => Some(EffectFamily::CompositionAL),
        "DealDamageEffect" => Some(EffectFamily::Combat),
        "DealDistributedDamageEffect" => Some(EffectFamily::Combat),
        "DestroyEffect" => Some(EffectFamily::ZoneLibrary),
        "DestroyNoRegenerationEffect" => Some(EffectFamily::ZoneLibrary),
        "DetainEffect" => Some(EffectFamily::Permanent),
        "DevourEffect" => Some(EffectFamily::CompositionAL),
        "DirectionalAdjacentPlayerControlEffect" => Some(EffectFamily::Permanent),
        "DiscardEffect" => Some(EffectFamily::ZoneLibrary),
        "DiscardHandEffect" => Some(EffectFamily::ZoneLibrary),
        "DiscoverEffect" => Some(EffectFamily::Player),
        "DoubleCountersEffect" => Some(EffectFamily::Resources),
        "DoubleManaPoolEffect" => Some(EffectFamily::Resources),
        "DrawCardsEffect" => Some(EffectFamily::ZoneLibrary),
        "DrawForEachTaggedMatchingEffect" => Some(EffectFamily::ZoneLibrary),
        "EachPlayerScryEffect" => Some(EffectFamily::ZoneLibrary),
        "EarthbendEffect" => Some(EffectFamily::Permanent),
        "EmitGiftGivenEffect" => Some(EffectFamily::CompositionAL),
        "EmitKeywordActionEffect" => Some(EffectFamily::CompositionAL),
        "EmptyManaPoolEffect" => Some(EffectFamily::Resources),
        "EndCombatPhaseEffect" => Some(EffectFamily::Player),
        "EndTurnEffect" => Some(EffectFamily::Player),
        "EnergyCountersEffect" => Some(EffectFamily::Player),
        "EvolveEffect" => Some(EffectFamily::Permanent),
        "ExchangeControlEffect" => Some(EffectFamily::Permanent),
        "ExchangeLifeTotalsEffect" => Some(EffectFamily::Resources),
        "ExchangeTextBoxesEffect" => Some(EffectFamily::Permanent),
        "ExchangeValuesEffect" => Some(EffectFamily::Combat),
        "ExchangeZonesEffect" => Some(EffectFamily::ZoneLibrary),
        "ExecuteWithSourceEffect" => Some(EffectFamily::CompositionAL),
        "ExertCostEffect" => Some(EffectFamily::Permanent),
        "ExileEffect" => Some(EffectFamily::ZoneLibrary),
        "ExileInsteadOfGraveyardEffect" => Some(EffectFamily::Player),
        "ExileTaggedWhenSourceLeavesEffect" => Some(EffectFamily::StackEvent),
        "ExileTopOfLibraryEffect" => Some(EffectFamily::ZoneLibrary),
        "ExileUntilEffect" => Some(EffectFamily::ZoneLibrary),
        "ExperienceCountersEffect" => Some(EffectFamily::Player),
        "ExploreEffect" => Some(EffectFamily::CompositionAL),
        "ExtraTurnAfterNextTurnEffect" => Some(EffectFamily::Player),
        "ExtraTurnEffect" => Some(EffectFamily::Player),
        "FatesealEffect" => Some(EffectFamily::ZoneLibrary),
        "FightEffect" => Some(EffectFamily::Combat),
        "FlipCoinEffect" => Some(EffectFamily::Player),
        "FlipEffect" => Some(EffectFamily::Permanent),
        "ForEachControllerOfTaggedEffect" => Some(EffectFamily::CompositionAL),
        "ForEachCounterKindPutOrRemoveEffect" => Some(EffectFamily::Resources),
        "ForEachObject" => Some(EffectFamily::CompositionAL),
        "ForEachObjectCorrelatedResultEffect" => Some(EffectFamily::CompositionAL),
        "ForEachTaggedEffect" => Some(EffectFamily::CompositionAL),
        "ForEachTaggedPlayerEffect" => Some(EffectFamily::CompositionAL),
        "ForPlayersEffect" => Some(EffectFamily::CompositionAL),
        "GainLifeEffect" => Some(EffectFamily::Resources),
        "GoadEffect" => Some(EffectFamily::Combat),
        "ClearGoadEffect" => Some(EffectFamily::Combat),
        "GrantAbilitiesTargetEffect" => Some(EffectFamily::Combat),
        "GrantBySpecEffect" => Some(EffectFamily::Player),
        "GrantEffect" => Some(EffectFamily::Player),
        "GrantNextSpellAbilityEffect" => Some(EffectFamily::Player),
        "GrantNextSpellCostReductionEffect" => Some(EffectFamily::Player),
        "GrantPlayTaggedEffect" => Some(EffectFamily::Player),
        "GrantRepeatableManaPaymentActionUntilEndOfTurnEffect" => Some(EffectFamily::CompositionAL),
        "GrantTaggedSpellFreeCastUntilEndOfTurnEffect" => Some(EffectFamily::Player),
        "GrantTaggedSpellLifeCostByManaValueEffect" => Some(EffectFamily::Player),
        "HauntExileEffect" => Some(EffectFamily::ZoneLibrary),
        "HealDamageEffect" => Some(EffectFamily::Combat),
        "IfEffect" => Some(EffectFamily::CompositionAL),
        "IncreaseSpeedEffect" => Some(EffectFamily::Player),
        "IncubateEffect" => Some(EffectFamily::Permanent),
        "InvestigateEffect" => Some(EffectFamily::Permanent),
        "LearnEffect" => Some(EffectFamily::ZoneLibrary),
        "LocalRewriteEffect" => Some(EffectFamily::CompositionAL),
        "LookAtHandEffect" => Some(EffectFamily::ZoneLibrary),
        "LookAtObjectsEffect" => Some(EffectFamily::ZoneLibrary),
        "LookAtTopCardsEffect" => Some(EffectFamily::ZoneLibrary),
        "LoseLifeEffect" => Some(EffectFamily::Resources),
        "LoseTheGameEffect" => Some(EffectFamily::Player),
        "ManaRestrictedEffect" => Some(EffectFamily::CompositionMZ),
        "ManaRetainedEffect" => Some(EffectFamily::CompositionMZ),
        "ManifestCardFromHandEffect" => Some(EffectFamily::CompositionMZ),
        "ManifestDreadEffect" => Some(EffectFamily::CompositionMZ),
        "ManifestObjectsEffect" => Some(EffectFamily::CompositionMZ),
        "ManifestTopCardOfLibraryEffect" => Some(EffectFamily::CompositionMZ),
        "MayCastMatchingSpellWithoutPayingManaCostEffect" => Some(EffectFamily::Player),
        "MayEffect" => Some(EffectFamily::CompositionMZ),
        "MayMoveToZoneEffect" => Some(EffectFamily::ZoneLibrary),
        "MeldEffect" => Some(EffectFamily::Permanent),
        "MillEffect" => Some(EffectFamily::ZoneLibrary),
        "ModifyPowerToughnessEffect" => Some(EffectFamily::Combat),
        "ModifyPowerToughnessForEachEffect" => Some(EffectFamily::Combat),
        "MonstrosityEffect" => Some(EffectFamily::Permanent),
        "MoveAllCountersEffect" => Some(EffectFamily::Resources),
        "MoveCountersEffect" => Some(EffectFamily::Resources),
        "MoveOneCounterEffect" => Some(EffectFamily::Resources),
        "MoveToLibraryNthFromTopEffect" => Some(EffectFamily::ZoneLibrary),
        "MoveToLibraryTopOrBottomChoiceEffect" => Some(EffectFamily::ZoneLibrary),
        "MoveToZoneEffect" => Some(EffectFamily::ZoneLibrary),
        "NinjutsuCostEffect" => Some(EffectFamily::Permanent),
        "NinjutsuEffect" => Some(EffectFamily::Permanent),
        "NoteLifeTotalEffect" => Some(EffectFamily::Resources),
        "OpenAttractionEffect" => Some(EffectFamily::CompositionMZ),
        "PayAnyEnergyEffect" => Some(EffectFamily::Player),
        "PayAnyLifeEffect" => Some(EffectFamily::Player),
        "PayEnergyEffect" => Some(EffectFamily::Player),
        "PayLifeEffect" => Some(EffectFamily::Resources),
        "PayManaEffect" => Some(EffectFamily::Resources),
        "PhaseInEffect" => Some(EffectFamily::Permanent),
        "PhaseOutEffect" => Some(EffectFamily::Permanent),
        "PlaySubgameEffect" => Some(EffectFamily::Player),
        "PoisonCountersEffect" => Some(EffectFamily::Player),
        "PopulateEffect" => Some(EffectFamily::CompositionMZ),
        "PrepareEffect" => Some(EffectFamily::Permanent),
        "PreventAllCombatDamageEffect" => Some(EffectFamily::Combat),
        "PreventAllDamageEffect" => Some(EffectFamily::Combat),
        "PreventAllDamageToTargetEffect" => Some(EffectFamily::Combat),
        "PreventDamageEffect" => Some(EffectFamily::Combat),
        "PreventNextTimeDamageEffect" => Some(EffectFamily::Combat),
        "ProliferateEffect" => Some(EffectFamily::Resources),
        "PutCounterOfChosenKindEffect" => Some(EffectFamily::Resources),
        "PutCountersEffect" => Some(EffectFamily::Resources),
        "PutOntoBattlefieldEffect" => Some(EffectFamily::ZoneLibrary),
        "PutStickerEffect" => Some(EffectFamily::Permanent),
        "PutTaggedRemainderOnLibraryBottomEffect" => Some(EffectFamily::ZoneLibrary),
        "RearrangeLookedCardsInLibraryEffect" => Some(EffectFamily::ZoneLibrary),
        "ReconfigureEffect" => Some(EffectFamily::Permanent),
        "RedirectAllDamageThisTurnToTargetEffect" => Some(EffectFamily::Combat),
        "RedirectNextDamageToTargetEffect" => Some(EffectFamily::Combat),
        "RedirectNextTimeDamageToSourceEffect" => Some(EffectFamily::Combat),
        "ReduceSpeedEffect" => Some(EffectFamily::Player),
        "ReflexiveTriggerEffect" => Some(EffectFamily::CompositionMZ),
        "RegenerateEffect" => Some(EffectFamily::Permanent),
        "RegisterDamagedBySourceZoneReplacementEffect" => Some(EffectFamily::StackEvent),
        "RegisterDrawReplacementEffect" => Some(EffectFamily::StackEvent),
        "RegisterEnterTappedReplacementEffect" => Some(EffectFamily::StackEvent),
        "RegisterEnterUnderControlReplacementEffect" => Some(EffectFamily::StackEvent),
        "RegisterFutureZoneReplacementEffect" => Some(EffectFamily::StackEvent),
        "RegisterManaReplacementEffect" => Some(EffectFamily::StackEvent),
        "RegisterEnterWithCountersReplacementEffect" => Some(EffectFamily::StackEvent),
        "RegisterNextBatchEnterWithCountersEffect" => Some(EffectFamily::StackEvent),
        "RegisterZoneReplacementEffect" => Some(EffectFamily::StackEvent),
        "RemoveAnyCountersAmongEffect" => Some(EffectFamily::Resources),
        "RemoveCountersEffect" => Some(EffectFamily::Resources),
        "RemoveFromCombatEffect" => Some(EffectFamily::Combat),
        "RemoveUpToAnyCountersEffect" => Some(EffectFamily::Resources),
        "RemoveUpToCountersEffect" => Some(EffectFamily::Resources),
        "RenownEffect" => Some(EffectFamily::Permanent),
        "ReorderGraveyardEffect" => Some(EffectFamily::ZoneLibrary),
        "ReorderLibraryTopEffect" => Some(EffectFamily::ZoneLibrary),
        "ReorderTopPlanarDeckEffect" => Some(EffectFamily::ZoneLibrary),
        "RepeatEffectsEffect" => Some(EffectFamily::CompositionMZ),
        "RepeatProcessEffect" => Some(EffectFamily::CompositionMZ),
        "RepeatProcessPromptEffect" => Some(EffectFamily::CompositionMZ),
        "ReplaceNextDamageToTargetEffect" => Some(EffectFamily::Combat),
        "RestartGameEffect" => Some(EffectFamily::Player),
        "RetainManaUntilEndOfTurnEffect" => Some(EffectFamily::Resources),
        "RetargetStackObjectEffect" => Some(EffectFamily::StackEvent),
        "ReturnAllToBattlefieldEffect" => Some(EffectFamily::ZoneLibrary),
        "ReturnFromGraveyardOrExileToBattlefieldEffect" => Some(EffectFamily::ZoneLibrary),
        "ReturnFromGraveyardToBattlefieldEffect" => Some(EffectFamily::ZoneLibrary),
        "ReturnFromGraveyardToHandEffect" => Some(EffectFamily::ZoneLibrary),
        "ReturnToHandEffect" => Some(EffectFamily::ZoneLibrary),
        "RevealFromHandEffect" => Some(EffectFamily::ZoneLibrary),
        "RevealSourceFromHandEffect" => Some(EffectFamily::ZoneLibrary),
        "RevealTaggedEffect" => Some(EffectFamily::ZoneLibrary),
        "RevealTopEffect" => Some(EffectFamily::ZoneLibrary),
        "ReverseTurnOrderEffect" => Some(EffectFamily::Player),
        "RingTemptsYouEffect" => Some(EffectFamily::Player),
        "RollDiceChooseResultEffect" => Some(EffectFamily::Player),
        "RollDieEffect" => Some(EffectFamily::Player),
        "SacrificeEffect" => Some(EffectFamily::ZoneLibrary),
        "SacrificePlayerEffect" => Some(EffectFamily::ZoneLibrary),
        "SacrificeTargetEffect" => Some(EffectFamily::ZoneLibrary),
        "ScheduleDelayedTriggerEffect" => Some(EffectFamily::StackEvent),
        "ScheduleEffectsWhenTaggedLeavesEffect" => Some(EffectFamily::StackEvent),
        "ScryEffect" => Some(EffectFamily::ZoneLibrary),
        "SearchLibraryEffect" => Some(EffectFamily::ZoneLibrary),
        "SearchLibrarySlotsEffect" => Some(EffectFamily::ZoneLibrary),
        "SecretChoiceEffect" => Some(EffectFamily::CompositionMZ),
        "SequenceEffect" => Some(EffectFamily::CompositionMZ),
        "SetBasePowerToughnessEffect" => Some(EffectFamily::Combat),
        "SetLifeTotalEffect" => Some(EffectFamily::Resources),
        "ShuffleGraveyardIntoLibraryEffect" => Some(EffectFamily::ZoneLibrary),
        "ShuffleHandAndGraveyardIntoLibraryEffect" => Some(EffectFamily::ZoneLibrary),
        "ShuffleLibraryEffect" => Some(EffectFamily::ZoneLibrary),
        "ShuffleObjectsIntoLibraryEffect" => Some(EffectFamily::ZoneLibrary),
        "SkipCombatPhasesEffect" => Some(EffectFamily::Player),
        "SkipCombatPhasesThisTurnEffect" => Some(EffectFamily::Player),
        "SkipDrawStepEffect" => Some(EffectFamily::Player),
        "SkipMainPhasesThisTurnEffect" => Some(EffectFamily::Player),
        "SkipNextCombatPhaseThisTurnEffect" => Some(EffectFamily::Player),
        "SkipTurnEffect" => Some(EffectFamily::Player),
        "SneakCostEffect" => Some(EffectFamily::Permanent),
        "SolveCaseEffect" => Some(EffectFamily::Permanent),
        "SoulbondPairEffect" => Some(EffectFamily::Permanent),
        "SupportEffect" => Some(EffectFamily::CompositionMZ),
        "SurveilEffect" => Some(EffectFamily::ZoneLibrary),
        "SuspectEffect" => Some(EffectFamily::Permanent),
        "TagAttachedToSourceEffect" => Some(EffectFamily::CompositionMZ),
        "TagMatchingObjectsEffect" => Some(EffectFamily::CompositionMZ),
        "TagOtherBlockParticipantEffect" => Some(EffectFamily::CompositionMZ),
        "TagTriggeringAttackerEffect" => Some(EffectFamily::CompositionMZ),
        "TagTriggeringBlockersEffect" => Some(EffectFamily::CompositionMZ),
        "TagTriggeringDamageTargetEffect" => Some(EffectFamily::CompositionMZ),
        "TagTriggeringObjectEffect" => Some(EffectFamily::CompositionMZ),
        "TagTriggeringSourceEffect" => Some(EffectFamily::CompositionMZ),
        "TaggedEffect" => Some(EffectFamily::CompositionMZ),
        "TakeInitiativeEffect" => Some(EffectFamily::Player),
        "TapEffect" => Some(EffectFamily::Permanent),
        "TargetOnlyEffect" => Some(EffectFamily::CompositionMZ),
        "TicketCountersEffect" => Some(EffectFamily::Player),
        "TransformEffect" => Some(EffectFamily::Permanent),
        "TurnFaceUpEffect" => Some(EffectFamily::Permanent),
        "UnattachObjectsEffect" => Some(EffectFamily::Permanent),
        "UnearthEffect" => Some(EffectFamily::Permanent),
        "UnlessActionEffect" => Some(EffectFamily::CompositionMZ),
        "UnlessPaysEffect" => Some(EffectFamily::CompositionMZ),
        "UnlockRoomDoorEffect" => Some(EffectFamily::Permanent),
        "UntapEffect" => Some(EffectFamily::Permanent),
        "VariableCasualtyPlaneswalkerCopyEffect" => Some(EffectFamily::StackEvent),
        "VentureIntoDungeonEffect" => Some(EffectFamily::Player),
        "VillainousChoiceEffect" => Some(EffectFamily::CompositionMZ),
        "VoteEffect" => Some(EffectFamily::CompositionMZ),
        "WinTheGameEffect" => Some(EffectFamily::Player),
        "WithIdEffect" => Some(EffectFamily::CompositionMZ),
        "ImprintFromHandEffect" => Some(EffectFamily::ZoneLibrary),
        "ScaleXValueEffect" => Some(EffectFamily::StackEvent),
        _ => None,
    }
}

pub fn decode(kind: &str, payload: Value) -> Result<ErasedPayload, String> {
    let decoded = match family_for_kind(kind) {
        Some(family) => match family {
            EffectFamily::ZoneLibrary => {
                ironsmith_runtime_effect_zone_library::decode(kind, payload)
            }
            EffectFamily::Player => ironsmith_runtime_effect_player::decode(kind, payload),
            EffectFamily::Resources => ironsmith_runtime_effect_resources::decode(kind, payload),
            EffectFamily::Permanent => ironsmith_runtime_effect_permanent::decode(kind, payload),
            EffectFamily::Combat => ironsmith_runtime_effect_combat::decode(kind, payload),
            EffectFamily::StackEvent => ironsmith_runtime_effect_stack_event::decode(kind, payload),
            EffectFamily::CompositionAL => {
                ironsmith_runtime_effect_composition_a_l::decode(kind, payload)
            }
            EffectFamily::CompositionMZ => {
                ironsmith_runtime_effect_composition_m_z::decode(kind, payload)
            }
        },
        None => return Err(format!("unknown compiled effect payload kind: {kind}")),
    }?;
    decoded.ok_or_else(|| format!("unknown compiled effect payload kind: {kind}"))
}

#[cfg(test)]
mod tests {
    use super::{EffectFamily, family_for_kind};

    #[test]
    fn routes_representative_effects_to_domain_families() {
        assert_eq!(
            family_for_kind("MoveToZoneEffect"),
            Some(EffectFamily::ZoneLibrary)
        );
        assert_eq!(
            family_for_kind("ChoosePlayerEffect"),
            Some(EffectFamily::Player)
        );
        assert_eq!(
            family_for_kind("AddManaEffect"),
            Some(EffectFamily::Resources)
        );
        assert_eq!(
            family_for_kind("CreateTokenEffect"),
            Some(EffectFamily::Permanent)
        );
        assert_eq!(
            family_for_kind("DealDamageEffect"),
            Some(EffectFamily::Combat)
        );
        assert_eq!(
            family_for_kind("CopySpellEffect"),
            Some(EffectFamily::StackEvent)
        );
        assert_eq!(
            family_for_kind("ChooseModeEffect"),
            Some(EffectFamily::CompositionAL)
        );
        assert_eq!(
            family_for_kind("WithIdEffect"),
            Some(EffectFamily::CompositionMZ)
        );
        assert_eq!(family_for_kind("NotAnEffect"), None);
    }
}
