//! Replacement effect helpers.

mod apply_replacement;
mod register_damaged_by_source_zone_replacement;
mod register_draw_replacement;
mod register_enter_tapped;
mod register_future_zone_replacement;
mod register_mana_replacement;
mod register_mana_rewrite;
mod register_mana_spend_permission;
mod register_next_batch_enter_with_counters;
mod register_counter_placement_replacement;
mod register_zone_replacement;

pub use apply_replacement::{ApplyReplacementEffect, ReplacementApplyMode};
pub use register_counter_placement_replacement::RegisterCounterPlacementReplacementEffect;
pub use register_damaged_by_source_zone_replacement::RegisterDamagedBySourceZoneReplacementEffect;
pub use register_draw_replacement::RegisterDrawReplacementEffect;
pub use register_enter_tapped::RegisterEnterTappedReplacementEffect;
pub use register_enter_under_control::RegisterEnterUnderControlReplacementEffect;
pub use register_future_zone_replacement::RegisterFutureZoneReplacementEffect;
pub use register_mana_replacement::RegisterManaReplacementEffect;
pub use register_mana_rewrite::RegisterManaRewriteEffect;
pub use register_mana_spend_permission::RegisterManaSpendPermissionEffect;
pub use register_next_batch_enter_with_counters::RegisterNextBatchEnterWithCountersEffect;
pub use register_zone_replacement::RegisterZoneReplacementEffect;

mod register_enter_under_control;
pub(crate) use register_zone_replacement::zone_replacement_action;

mod register_enter_with_counters;
pub use register_enter_with_counters::RegisterEnterWithCountersReplacementEffect;

mod execute_payload;
pub(crate) use execute_payload::{execute_replacement_payload, execute_replacement_payload_with_object_tags, execute_event_expansion, execute_event_expansion_with_targets, execute_deferred_replacement_programs, execute_deferred_replacement_programs_with_targets};

pub(crate) use execute_payload::{ReplacementProgramBindings, execute_event_expansion_with_bindings, execute_deferred_replacement_programs_with_bindings};

mod register_damage_multiplier;
mod register_damage_addition;
pub use register_damage_multiplier::RegisterDamageMultiplierEffect;
pub use register_damage_addition::RegisterDamageAdditionEffect;

mod draw_continuation;
pub(crate) use draw_continuation::prepare_draw_continuation;

pub(crate) use draw_continuation::{PreparedReplacementChild, ReplacementResume, prepare_replacement_child, replacement_effect_contains_draw};

pub(crate) use draw_continuation::prepare_draw_continuation_with_bindings;

pub(crate) use execute_payload::execute_replacement_payload_with_snapshot;

pub(crate) use execute_payload::with_replacement_child;
